### ISSUE TITLE
set a lang to user profile doesnt default drupal client to this lang

### ISSUE THREAD

**Issue by tdemalliard** [obiba/agate-drupal7#99]
# Versions
Mica Client 7.x-34.9
Agate 1.4.6

# Reproduce
1. drupal client: configure 2 lang with their path prefix : en and fr
1. User: set the lang to fr -> save
1. remove the path prefix or logout/login back
1. lang is default, english

# more doc
**configuration of language detection**
![image](https://user-images.githubusercontent.com/3911087/59768306-22d7b600-9272-11e9-8b5d-b5776b643187.png)

**Config English**
![image](https://user-images.githubusercontent.com/3911087/59768363-3a16a380-9272-11e9-9cd9-e58f6fe46e29.png)

**Config french**
![image](https://user-images.githubusercontent.com/3911087/59768390-4864bf80-9272-11e9-9d2b-9a1cba275a21.png)

**Comment by smirfolio** [comment]
Seems that when updating the User profile the chosen user language don't take effect.
A fix will be applied  to the 7.x-35.x and master branch

**Comment by smirfolio** [comment]
A fix is available : https://www.drupal.org/project/obiba_agate/releases/7.x-2.9
